// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: email.proto

package pb_email

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// EmailListenerClient is the client API for EmailListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailListenerClient interface {
}

type emailListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailListenerClient(cc grpc.ClientConnInterface) EmailListenerClient {
	return &emailListenerClient{cc}
}

// EmailListenerServer is the server API for EmailListener service.
// All implementations must embed UnimplementedEmailListenerServer
// for forward compatibility.
type EmailListenerServer interface {
	mustEmbedUnimplementedEmailListenerServer()
}

// UnimplementedEmailListenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailListenerServer struct{}

func (UnimplementedEmailListenerServer) mustEmbedUnimplementedEmailListenerServer() {}
func (UnimplementedEmailListenerServer) testEmbeddedByValue()                       {}

// UnsafeEmailListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailListenerServer will
// result in compilation errors.
type UnsafeEmailListenerServer interface {
	mustEmbedUnimplementedEmailListenerServer()
}

func RegisterEmailListenerServer(s grpc.ServiceRegistrar, srv EmailListenerServer) {
	// If the following call pancis, it indicates UnimplementedEmailListenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailListener_ServiceDesc, srv)
}

// EmailListener_ServiceDesc is the grpc.ServiceDesc for EmailListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EmailListener",
	HandlerType: (*EmailListenerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "email.proto",
}
