// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: publication-authorization.proto

package pb_publication_authorization

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicationAuthorization_IsAuthorizedPublisher_FullMethodName = "/PublicationAuthorization/IsAuthorizedPublisher"
)

// PublicationAuthorizationClient is the client API for PublicationAuthorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicationAuthorizationClient interface {
	IsAuthorizedPublisher(ctx context.Context, in *IsAuthorizedPublisherRequest, opts ...grpc.CallOption) (*Response, error)
}

type publicationAuthorizationClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicationAuthorizationClient(cc grpc.ClientConnInterface) PublicationAuthorizationClient {
	return &publicationAuthorizationClient{cc}
}

func (c *publicationAuthorizationClient) IsAuthorizedPublisher(ctx context.Context, in *IsAuthorizedPublisherRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PublicationAuthorization_IsAuthorizedPublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicationAuthorizationServer is the server API for PublicationAuthorization service.
// All implementations must embed UnimplementedPublicationAuthorizationServer
// for forward compatibility.
type PublicationAuthorizationServer interface {
	IsAuthorizedPublisher(context.Context, *IsAuthorizedPublisherRequest) (*Response, error)
	mustEmbedUnimplementedPublicationAuthorizationServer()
}

// UnimplementedPublicationAuthorizationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicationAuthorizationServer struct{}

func (UnimplementedPublicationAuthorizationServer) IsAuthorizedPublisher(context.Context, *IsAuthorizedPublisherRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuthorizedPublisher not implemented")
}
func (UnimplementedPublicationAuthorizationServer) mustEmbedUnimplementedPublicationAuthorizationServer() {
}
func (UnimplementedPublicationAuthorizationServer) testEmbeddedByValue() {}

// UnsafePublicationAuthorizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicationAuthorizationServer will
// result in compilation errors.
type UnsafePublicationAuthorizationServer interface {
	mustEmbedUnimplementedPublicationAuthorizationServer()
}

func RegisterPublicationAuthorizationServer(s grpc.ServiceRegistrar, srv PublicationAuthorizationServer) {
	// If the following call pancis, it indicates UnimplementedPublicationAuthorizationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicationAuthorization_ServiceDesc, srv)
}

func _PublicationAuthorization_IsAuthorizedPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicationAuthorizationServer).IsAuthorizedPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicationAuthorization_IsAuthorizedPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicationAuthorizationServer).IsAuthorizedPublisher(ctx, req.(*IsAuthorizedPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicationAuthorization_ServiceDesc is the grpc.ServiceDesc for PublicationAuthorization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicationAuthorization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PublicationAuthorization",
	HandlerType: (*PublicationAuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAuthorizedPublisher",
			Handler:    _PublicationAuthorization_IsAuthorizedPublisher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publication-authorization.proto",
}
