// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.21.12
// source: orchestrator/pkg/grpc/proto/auth-manager.proto

package pb_auth_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreatePublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PlanId        int32                  `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePublisherRequest) Reset() {
	*x = CreatePublisherRequest{}
	mi := &file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublisherRequest) ProtoMessage() {}

func (x *CreatePublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublisherRequest.ProtoReflect.Descriptor instead.
func (*CreatePublisherRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePublisherRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreatePublisherRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *CreatePublisherRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RollbackCreatePublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackCreatePublisherRequest) Reset() {
	*x = RollbackCreatePublisherRequest{}
	mi := &file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackCreatePublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackCreatePublisherRequest) ProtoMessage() {}

func (x *RollbackCreatePublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackCreatePublisherRequest.ProtoReflect.Descriptor instead.
func (*RollbackCreatePublisherRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackCreatePublisherRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_orchestrator_pkg_grpc_proto_auth_manager_proto protoreflect.FileDescriptor

var file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x23, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x39, 0x0a, 0x1e, 0x52, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x8b, 0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x17,
	0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x3b, 0x70, 0x62, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescOnce sync.Once
	file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescData = file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDesc
)

func file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescGZIP() []byte {
	file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescOnce.Do(func() {
		file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescData)
	})
	return file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDescData
}

var file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orchestrator_pkg_grpc_proto_auth_manager_proto_goTypes = []any{
	(*Response)(nil),                       // 0: Response
	(*CreatePublisherRequest)(nil),         // 1: CreatePublisherRequest
	(*RollbackCreatePublisherRequest)(nil), // 2: RollbackCreatePublisherRequest
}
var file_orchestrator_pkg_grpc_proto_auth_manager_proto_depIdxs = []int32{
	1, // 0: AuthManager.CreatePublisher:input_type -> CreatePublisherRequest
	2, // 1: AuthManager.RollbackCreatePublisher:input_type -> RollbackCreatePublisherRequest
	0, // 2: AuthManager.CreatePublisher:output_type -> Response
	0, // 3: AuthManager.RollbackCreatePublisher:output_type -> Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orchestrator_pkg_grpc_proto_auth_manager_proto_init() }
func file_orchestrator_pkg_grpc_proto_auth_manager_proto_init() {
	if File_orchestrator_pkg_grpc_proto_auth_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_pkg_grpc_proto_auth_manager_proto_goTypes,
		DependencyIndexes: file_orchestrator_pkg_grpc_proto_auth_manager_proto_depIdxs,
		MessageInfos:      file_orchestrator_pkg_grpc_proto_auth_manager_proto_msgTypes,
	}.Build()
	File_orchestrator_pkg_grpc_proto_auth_manager_proto = out.File
	file_orchestrator_pkg_grpc_proto_auth_manager_proto_rawDesc = nil
	file_orchestrator_pkg_grpc_proto_auth_manager_proto_goTypes = nil
	file_orchestrator_pkg_grpc_proto_auth_manager_proto_depIdxs = nil
}
