// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: content.proto

package pb_content

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// ContentListenerClient is the client API for ContentListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentListenerClient interface {
}

type contentListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewContentListenerClient(cc grpc.ClientConnInterface) ContentListenerClient {
	return &contentListenerClient{cc}
}

// ContentListenerServer is the server API for ContentListener service.
// All implementations must embed UnimplementedContentListenerServer
// for forward compatibility.
type ContentListenerServer interface {
	mustEmbedUnimplementedContentListenerServer()
}

// UnimplementedContentListenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentListenerServer struct{}

func (UnimplementedContentListenerServer) mustEmbedUnimplementedContentListenerServer() {}
func (UnimplementedContentListenerServer) testEmbeddedByValue()                         {}

// UnsafeContentListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentListenerServer will
// result in compilation errors.
type UnsafeContentListenerServer interface {
	mustEmbedUnimplementedContentListenerServer()
}

func RegisterContentListenerServer(s grpc.ServiceRegistrar, srv ContentListenerServer) {
	// If the following call pancis, it indicates UnimplementedContentListenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentListener_ServiceDesc, srv)
}

// ContentListener_ServiceDesc is the grpc.ServiceDesc for ContentListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ContentListener",
	HandlerType: (*ContentListenerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "content.proto",
}
