// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.21.12
// source: email/pkg/grpc/proto/email-service.proto

package pb_email_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriberRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriberRegistration) Reset() {
	*x = SubscriberRegistration{}
	mi := &file_email_pkg_grpc_proto_email_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriberRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberRegistration) ProtoMessage() {}

func (x *SubscriberRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_email_pkg_grpc_proto_email_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberRegistration.ProtoReflect.Descriptor instead.
func (*SubscriberRegistration) Descriptor() ([]byte, []int) {
	return file_email_pkg_grpc_proto_email_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriberRegistration) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriberRegistration) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PublisherRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PlanId        int32                  `protobuf:"varint,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherRegistration) Reset() {
	*x = PublisherRegistration{}
	mi := &file_email_pkg_grpc_proto_email_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherRegistration) ProtoMessage() {}

func (x *PublisherRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_email_pkg_grpc_proto_email_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherRegistration.ProtoReflect.Descriptor instead.
func (*PublisherRegistration) Descriptor() ([]byte, []int) {
	return file_email_pkg_grpc_proto_email_service_proto_rawDescGZIP(), []int{1}
}

func (x *PublisherRegistration) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublisherRegistration) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PublisherRegistration) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_email_pkg_grpc_proto_email_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_email_pkg_grpc_proto_email_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_email_pkg_grpc_proto_email_service_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_email_pkg_grpc_proto_email_service_proto protoreflect.FileDescriptor

var file_email_pkg_grpc_proto_email_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x16, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0x5f, 0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x6e, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x82, 0x01, 0x0a, 0x0c, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x13, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x4e, 0x65, 0x77, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x72, 0x12, 0x17, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x4e, 0x65, 0x77, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x21, 0x5a, 0x1f, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x3b, 0x70, 0x62, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_email_pkg_grpc_proto_email_service_proto_rawDescOnce sync.Once
	file_email_pkg_grpc_proto_email_service_proto_rawDescData = file_email_pkg_grpc_proto_email_service_proto_rawDesc
)

func file_email_pkg_grpc_proto_email_service_proto_rawDescGZIP() []byte {
	file_email_pkg_grpc_proto_email_service_proto_rawDescOnce.Do(func() {
		file_email_pkg_grpc_proto_email_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_email_pkg_grpc_proto_email_service_proto_rawDescData)
	})
	return file_email_pkg_grpc_proto_email_service_proto_rawDescData
}

var file_email_pkg_grpc_proto_email_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_email_pkg_grpc_proto_email_service_proto_goTypes = []any{
	(*SubscriberRegistration)(nil), // 0: SubscriberRegistration
	(*PublisherRegistration)(nil),  // 1: PublisherRegistration
	(*Response)(nil),               // 2: Response
}
var file_email_pkg_grpc_proto_email_service_proto_depIdxs = []int32{
	0, // 0: EmailService.NotifyNewSubscriber:input_type -> SubscriberRegistration
	1, // 1: EmailService.NotifyNewPublisher:input_type -> PublisherRegistration
	2, // 2: EmailService.NotifyNewSubscriber:output_type -> Response
	2, // 3: EmailService.NotifyNewPublisher:output_type -> Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_email_pkg_grpc_proto_email_service_proto_init() }
func file_email_pkg_grpc_proto_email_service_proto_init() {
	if File_email_pkg_grpc_proto_email_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_email_pkg_grpc_proto_email_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_pkg_grpc_proto_email_service_proto_goTypes,
		DependencyIndexes: file_email_pkg_grpc_proto_email_service_proto_depIdxs,
		MessageInfos:      file_email_pkg_grpc_proto_email_service_proto_msgTypes,
	}.Build()
	File_email_pkg_grpc_proto_email_service_proto = out.File
	file_email_pkg_grpc_proto_email_service_proto_rawDesc = nil
	file_email_pkg_grpc_proto_email_service_proto_goTypes = nil
	file_email_pkg_grpc_proto_email_service_proto_depIdxs = nil
}
