// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.21.12
// source: subscription/pkg/grpc/proto/subscription-manager.proto

package pb_subscription_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type CreateSubscriptionForPublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        int32                  `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionForPublisherRequest) Reset() {
	*x = CreateSubscriptionForPublisherRequest{}
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionForPublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionForPublisherRequest) ProtoMessage() {}

func (x *CreateSubscriptionForPublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionForPublisherRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionForPublisherRequest) Descriptor() ([]byte, []int) {
	return file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionForPublisherRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSubscriptionForPublisherRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type GetContentSubscribersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicationId int32                  `protobuf:"varint,1,opt,name=publication_id,json=publicationId,proto3" json:"publication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentSubscribersRequest) Reset() {
	*x = GetContentSubscribersRequest{}
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentSubscribersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentSubscribersRequest) ProtoMessage() {}

func (x *GetContentSubscribersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentSubscribersRequest.ProtoReflect.Descriptor instead.
func (*GetContentSubscribersRequest) Descriptor() ([]byte, []int) {
	return file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentSubscribersRequest) GetPublicationId() int32 {
	if x != nil {
		return x.PublicationId
	}
	return 0
}

type GetContentSubscribersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberIds []int32                `protobuf:"varint,1,rep,packed,name=subscriber_ids,json=subscriberIds,proto3" json:"subscriber_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentSubscribersResponse) Reset() {
	*x = GetContentSubscribersResponse{}
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentSubscribersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentSubscribersResponse) ProtoMessage() {}

func (x *GetContentSubscribersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentSubscribersResponse.ProtoReflect.Descriptor instead.
func (*GetContentSubscribersResponse) Descriptor() ([]byte, []int) {
	return file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentSubscribersResponse) GetSubscriberIds() []int32 {
	if x != nil {
		return x.SubscriberIds
	}
	return nil
}

var File_subscription_pkg_grpc_proto_subscription_manager_proto protoreflect.FileDescriptor

var file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDesc = []byte{
	0x0a, 0x36, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x59, 0x0a, 0x25, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x45,
	0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x49, 0x64, 0x73, 0x32, 0xc2, 0x01,
	0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x53, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x26, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x2e, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x3b, 0x70, 0x62, 0x5f,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescOnce sync.Once
	file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescData = file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDesc
)

func file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescGZIP() []byte {
	file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescOnce.Do(func() {
		file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescData)
	})
	return file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDescData
}

var file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_subscription_pkg_grpc_proto_subscription_manager_proto_goTypes = []any{
	(*Response)(nil), // 0: Response
	(*CreateSubscriptionForPublisherRequest)(nil), // 1: CreateSubscriptionForPublisherRequest
	(*GetContentSubscribersRequest)(nil),          // 2: GetContentSubscribersRequest
	(*GetContentSubscribersResponse)(nil),         // 3: GetContentSubscribersResponse
}
var file_subscription_pkg_grpc_proto_subscription_manager_proto_depIdxs = []int32{
	1, // 0: SubscriptionManager.CreateSubscriptionForPublisher:input_type -> CreateSubscriptionForPublisherRequest
	2, // 1: SubscriptionManager.GetContentSubscribers:input_type -> GetContentSubscribersRequest
	0, // 2: SubscriptionManager.CreateSubscriptionForPublisher:output_type -> Response
	3, // 3: SubscriptionManager.GetContentSubscribers:output_type -> GetContentSubscribersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscription_pkg_grpc_proto_subscription_manager_proto_init() }
func file_subscription_pkg_grpc_proto_subscription_manager_proto_init() {
	if File_subscription_pkg_grpc_proto_subscription_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_pkg_grpc_proto_subscription_manager_proto_goTypes,
		DependencyIndexes: file_subscription_pkg_grpc_proto_subscription_manager_proto_depIdxs,
		MessageInfos:      file_subscription_pkg_grpc_proto_subscription_manager_proto_msgTypes,
	}.Build()
	File_subscription_pkg_grpc_proto_subscription_manager_proto = out.File
	file_subscription_pkg_grpc_proto_subscription_manager_proto_rawDesc = nil
	file_subscription_pkg_grpc_proto_subscription_manager_proto_goTypes = nil
	file_subscription_pkg_grpc_proto_subscription_manager_proto_depIdxs = nil
}
