// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: subscription/pkg/grpc/proto/subscription-manager.proto

package pb_subscription_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionManager_CreateSubscriptionForPublisher_FullMethodName         = "/SubscriptionManager/CreateSubscriptionForPublisher"
	SubscriptionManager_GetContentSubscribers_FullMethodName                  = "/SubscriptionManager/GetContentSubscribers"
	SubscriptionManager_RollbackCreateSubscriptionForPublisher_FullMethodName = "/SubscriptionManager/RollbackCreateSubscriptionForPublisher"
)

// SubscriptionManagerClient is the client API for SubscriptionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionManagerClient interface {
	CreateSubscriptionForPublisher(ctx context.Context, in *CreateSubscriptionForPublisherRequest, opts ...grpc.CallOption) (*CreateSubscriptionForPublisherResponse, error)
	GetContentSubscribers(ctx context.Context, in *GetContentSubscribersRequest, opts ...grpc.CallOption) (*GetContentSubscribersResponse, error)
	RollbackCreateSubscriptionForPublisher(ctx context.Context, in *RollbackCreateSubscriptionForPublisherRequest, opts ...grpc.CallOption) (*Response, error)
}

type subscriptionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionManagerClient(cc grpc.ClientConnInterface) SubscriptionManagerClient {
	return &subscriptionManagerClient{cc}
}

func (c *subscriptionManagerClient) CreateSubscriptionForPublisher(ctx context.Context, in *CreateSubscriptionForPublisherRequest, opts ...grpc.CallOption) (*CreateSubscriptionForPublisherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionForPublisherResponse)
	err := c.cc.Invoke(ctx, SubscriptionManager_CreateSubscriptionForPublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) GetContentSubscribers(ctx context.Context, in *GetContentSubscribersRequest, opts ...grpc.CallOption) (*GetContentSubscribersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentSubscribersResponse)
	err := c.cc.Invoke(ctx, SubscriptionManager_GetContentSubscribers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) RollbackCreateSubscriptionForPublisher(ctx context.Context, in *RollbackCreateSubscriptionForPublisherRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SubscriptionManager_RollbackCreateSubscriptionForPublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionManagerServer is the server API for SubscriptionManager service.
// All implementations must embed UnimplementedSubscriptionManagerServer
// for forward compatibility.
type SubscriptionManagerServer interface {
	CreateSubscriptionForPublisher(context.Context, *CreateSubscriptionForPublisherRequest) (*CreateSubscriptionForPublisherResponse, error)
	GetContentSubscribers(context.Context, *GetContentSubscribersRequest) (*GetContentSubscribersResponse, error)
	RollbackCreateSubscriptionForPublisher(context.Context, *RollbackCreateSubscriptionForPublisherRequest) (*Response, error)
	mustEmbedUnimplementedSubscriptionManagerServer()
}

// UnimplementedSubscriptionManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionManagerServer struct{}

func (UnimplementedSubscriptionManagerServer) CreateSubscriptionForPublisher(context.Context, *CreateSubscriptionForPublisherRequest) (*CreateSubscriptionForPublisherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscriptionForPublisher not implemented")
}
func (UnimplementedSubscriptionManagerServer) GetContentSubscribers(context.Context, *GetContentSubscribersRequest) (*GetContentSubscribersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentSubscribers not implemented")
}
func (UnimplementedSubscriptionManagerServer) RollbackCreateSubscriptionForPublisher(context.Context, *RollbackCreateSubscriptionForPublisherRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackCreateSubscriptionForPublisher not implemented")
}
func (UnimplementedSubscriptionManagerServer) mustEmbedUnimplementedSubscriptionManagerServer() {}
func (UnimplementedSubscriptionManagerServer) testEmbeddedByValue()                             {}

// UnsafeSubscriptionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionManagerServer will
// result in compilation errors.
type UnsafeSubscriptionManagerServer interface {
	mustEmbedUnimplementedSubscriptionManagerServer()
}

func RegisterSubscriptionManagerServer(s grpc.ServiceRegistrar, srv SubscriptionManagerServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionManager_ServiceDesc, srv)
}

func _SubscriptionManager_CreateSubscriptionForPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionForPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).CreateSubscriptionForPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionManager_CreateSubscriptionForPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).CreateSubscriptionForPublisher(ctx, req.(*CreateSubscriptionForPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_GetContentSubscribers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentSubscribersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).GetContentSubscribers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionManager_GetContentSubscribers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).GetContentSubscribers(ctx, req.(*GetContentSubscribersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_RollbackCreateSubscriptionForPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackCreateSubscriptionForPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).RollbackCreateSubscriptionForPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionManager_RollbackCreateSubscriptionForPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).RollbackCreateSubscriptionForPublisher(ctx, req.(*RollbackCreateSubscriptionForPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionManager_ServiceDesc is the grpc.ServiceDesc for SubscriptionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SubscriptionManager",
	HandlerType: (*SubscriptionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubscriptionForPublisher",
			Handler:    _SubscriptionManager_CreateSubscriptionForPublisher_Handler,
		},
		{
			MethodName: "GetContentSubscribers",
			Handler:    _SubscriptionManager_GetContentSubscribers_Handler,
		},
		{
			MethodName: "RollbackCreateSubscriptionForPublisher",
			Handler:    _SubscriptionManager_RollbackCreateSubscriptionForPublisher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscription/pkg/grpc/proto/subscription-manager.proto",
}
