// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: subscription.proto

package pb_subscription

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AskSubscription_GetContentSubscribers_FullMethodName = "/AskSubscription/GetContentSubscribers"
)

// AskSubscriptionClient is the client API for AskSubscription service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AskSubscriptionClient interface {
	GetContentSubscribers(ctx context.Context, in *GetContentSubscribersRequest, opts ...grpc.CallOption) (*GetContentSubscribersResponse, error)
}

type askSubscriptionClient struct {
	cc grpc.ClientConnInterface
}

func NewAskSubscriptionClient(cc grpc.ClientConnInterface) AskSubscriptionClient {
	return &askSubscriptionClient{cc}
}

func (c *askSubscriptionClient) GetContentSubscribers(ctx context.Context, in *GetContentSubscribersRequest, opts ...grpc.CallOption) (*GetContentSubscribersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentSubscribersResponse)
	err := c.cc.Invoke(ctx, AskSubscription_GetContentSubscribers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AskSubscriptionServer is the server API for AskSubscription service.
// All implementations must embed UnimplementedAskSubscriptionServer
// for forward compatibility.
type AskSubscriptionServer interface {
	GetContentSubscribers(context.Context, *GetContentSubscribersRequest) (*GetContentSubscribersResponse, error)
	mustEmbedUnimplementedAskSubscriptionServer()
}

// UnimplementedAskSubscriptionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAskSubscriptionServer struct{}

func (UnimplementedAskSubscriptionServer) GetContentSubscribers(context.Context, *GetContentSubscribersRequest) (*GetContentSubscribersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentSubscribers not implemented")
}
func (UnimplementedAskSubscriptionServer) mustEmbedUnimplementedAskSubscriptionServer() {}
func (UnimplementedAskSubscriptionServer) testEmbeddedByValue()                         {}

// UnsafeAskSubscriptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AskSubscriptionServer will
// result in compilation errors.
type UnsafeAskSubscriptionServer interface {
	mustEmbedUnimplementedAskSubscriptionServer()
}

func RegisterAskSubscriptionServer(s grpc.ServiceRegistrar, srv AskSubscriptionServer) {
	// If the following call pancis, it indicates UnimplementedAskSubscriptionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AskSubscription_ServiceDesc, srv)
}

func _AskSubscription_GetContentSubscribers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentSubscribersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskSubscriptionServer).GetContentSubscribers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AskSubscription_GetContentSubscribers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskSubscriptionServer).GetContentSubscribers(ctx, req.(*GetContentSubscribersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AskSubscription_ServiceDesc is the grpc.ServiceDesc for AskSubscription service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AskSubscription_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AskSubscription",
	HandlerType: (*AskSubscriptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContentSubscribers",
			Handler:    _AskSubscription_GetContentSubscribers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscription.proto",
}
